### ISSUE TITLE
Add /auth command

### ISSUE THREAD

**Issue by chelaxian** [joybiswas007/node-midjourney-telegram-bot#3]
Also would be great if you can add /auth + "password" command to protect bot from anauthorized uses

**Comment by joybiswas007** [comment]
> Also would be great if you can add /auth + "password" command to protect bot from anauthorized uses

Added to todolist.

**Comment by joybiswas007** [comment]
> or maybe just add on .env file whitelist variable with chat/user telegram IDs allowed to interract with bot

I'll try to add that feature whenever I get the time. Thanks for being patient.

**Comment by joybiswas007** [comment]
Feature added issue fixed.

**Comment by joybiswas007** [comment]
> wow! it works even for chats! thank you very much! love it ❤️

Glad to hear that :sunglasses:
